config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/services', to: 'static_pages#services'
  get '/bondstrand-pipe', to: 'static_pages#bondstrand-pipe'
  get '/contact', to: 'static_pages#contact'
  get '/photos', to: 'static_pages#photos'
  get '/page', to: 'static_pages#page'

  get '/gallery', to: 'photos#index', as: 'gallery'
  get 'photos/hello'
end

app/models/Photo.rb
class Photo
	include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :image_id, :image_src, :image_path, :image_title
  validates_presence_of :image_id, :image_src, :image_path, :image_title

		# def initialize(s,t,p)
  #     @image_src, @image_title, @image_path = image_src, image_title, image_path
  #   end



	# def show_photo()
 #    puts "<%= link_to(image_tag('gallery/#@image_src', alt: 'MANATEE SHIP REPAIR AND FABRICATION PROJECT GALLERY - #@image_id', class: 'img-responsive'), image_path('#@image_path'), data: { lightbox: 'example-set', title: '#@image_title' }) >"
 #  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  layout 'photo-application'
	def index
    @photo = Photo.new
    @image = [@image_src, @image_title, @image_path]
    @linkto = "<%= link_to(image_tag('gallery/#@image_src', alt: 'MANATEE SHIP REPAIR AND FABRICATION PROJECT GALLERY - #@image_title', class: 'img-responsive'), image_path('#@image_path'), data: { lightbox: 'example-set', title: '#@image_title' }) %>"

    @link = "<%= image_tag('https://s3.amazonaws.com/manatee-ship/gallery/manatee-gallery"
    @end = ".jpg', class:'img-responsive')%>"
    @ab = [1,2,3]
    @gallery = "<%= image_tag('https://s3.amazonaws.com/manatee-ship/gallery/manatee-gallery#@image_src.jpg', class: 'img-responsive gall') %>"

  	def show_photo()
  		puts linkto
    end

  end

  def hello
    @array = [1,2,3,4,5]
    @id = params['id']
    @page = params[:page]
    @image = params[:image]

    render('hello')
  end

  private
  	def photo_params
		  params.require(:photo).permit(:image_src, :image_title, :image_path)
		end
end

# photo1=Photo.new("gallery1.jpg", "1", "gallery1.jpg", "Image 1")
# @photo = Photo.new(:image_src => @image.src, :image_title => @image.title, :image_path => @image.path)

# gallery = IO.readlines("list.txt")
# puts gallery[0]
# puts gallery[1]

#  def initialize(w,h)
#     @width, @height = w, h
#  end

#  def to_s
#     "(w:#@width,h:#@height)"
#  end

# @box = Box.new(10, 20)
# puts "String representation of box is : #{box}"

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def bondstrand_pipe
	end

	def contact
	end

	def photos
		@gallery = "https://s3.amazonaws.com/manatee-ship/gallery/manatee-gallery"
	end

	def services
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="inner">
		<div class="fblock one">
			<p>Manatee Ship Repair and Fabrication is conveniently located at the mouth of Tampa Bay. We have an incredibly experienced team, and a reputation for prompt service and quality work. </p>

			<%=image_tag('manatee-logo.png', class: 'img-responsive flogo', alt: 'Manatee Ship Repair and Fabrication footer, logo') %>
		</div>

		<div class="fblock two">
			<h4>Contact Us for a Quote</h4>
			<div class="title-line"></div>
			<p class="border"><%= number_to_phone(9414172613, delimiter: '-') %></p>
		  <p class="border">info@manateeshiprepair.com</p>
		  <p>13604 Reeder Road<br> Palmetto, FL 34221</p>
			<%= link_to('View Map', 'https://www.google.com/maps/place/13604+Reeder+Rd,+Palmetto,+FL+34221/@27.6373153,-82.5481234,15z/data=!4m2!3m1!1s0x88c321f1253d981d:0x94e36849ead2e9a4', target: '_blank', class: 'map') %>
		</div>

		<div class="fblock three">
			<h4>We offer:</h4>
			<div class="title-line"></div>
			<ul>
				<li>Topside Ship Repairs of all Nature</li>
				<li>Structural Fabrication</li>
				<li>Bondstrand Repair and Fabrication</li>
				<li>Ballast Water Treatment Systems</li>
			</ul>
			<%= link_to('View All Services', services_path, target: '_blank', class: 'slink') %>
		</div>
		<span class="div"></span>

		<div class="copy">
			<div class="left"><p>© <%= Date.today.year %> Port Manatee Ship Repair and Fabrication.</p></div>
			<div class="right"><p>All rights reserved. Designed by <%=link_to('High Seas Design House', 'http://hsdesignhouse.com', target: '_blank') %>.</p></div>
		</div>
	</div>
  <!-- <a href="#" class="scroll-up">Scroll</a> -->
  <a href="#" class="scroll-up">Scroll<i class="fa fa-up"></i></a>

</footer>
<!-- Off Canvas Menu -->
<div class="offcanvas-menu">
		<div class="tmod">
	    <h3 class="module-title">Main Menu</h3>
	    <a class="close-offcanvas" href="#"><i class="rt-icon2-triangle-right"></i></a>
	  </div>

    <div class="offcanvas-inner">
        <div class="module">
            <div class="module-content">
              <ul class="nav menu">
                <%= render 'layouts/nav' %>
                <li class="quote">
                	Contact Us for a Quote:<br>
                	<%= number_to_phone(9414172613, delimiter: '-') %>
                </li>
              </ul>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<header class="header-style">
	<div class="container top">
		<div class="logo-block"><%= link_to(image_tag( 'manatee-logo.png', alt: 'Manatee Ship Repair & Fabrication Logo', class: 'img-responsive logo-img'), root_path ) %></div>
		<span class="mob-border"></span>


		<div class="info">
	  	<div class="phone"><span>Give Us a Call:</span><br> 941-417-2613</div>
	  	<div class="contact"><span>Email Us:</span><br> info@manateeshiprepair.com</div>
	  	<div class="quote"><p>Contact us for a quote!</p></div>
	  </div>

	  <div>
	    <a href="#" id="offcanvas-toggler">
	        <span></span>
	        <span></span>
	        <span></span>
	    </a>
	  </div>
	</div>
	<div class="clearfix"></div>

		<div class="nav-bottom">
			<ul class="site-nav">
        <%= render 'layouts/nav' %>
			</ul>
		</div>
	</div>
</header>

app/views/layouts/_nav.html.erb
<li class="menu-item"><%= link_to "Home", root_path %></li>
<li class="menu-item"><%= link_to "All Services", services_path %></li>
<li class="menu-item"><%= link_to "Bondstrand Pipe Repair", bondstrand_pipe_path %></li>
<li class="menu-item"><%= link_to "Project Gallery", photos_path %></li>
<li class="menu-item"><%= link_to "Contact", contact_path %></li>

app/views/layouts/_rails_default.html.erb
<!--  	<meta name="description" content= "<%= @page_description %>">
 	<link rel="shortcut icon" href="favicon.png">
  <title><%= @page_title  %> | Manatee Ship Repair &amp; Fabrication Logo</title>

	<%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
 <!-- http://manateeshiprepair.com/ -->
<!DOCTYPE html>
<html lang="en">
 <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content= "<%= @page_description %>">
    <link rel="shortcut icon" href="favicon.png">
    <title><%= @page_title %> | Manatee Ship Repair &amp; Fabrication Logo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% unless current_page?(photos_path) %> <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> <% end %>
    <%= render 'layouts/shim' %>
  </head>

    <body class=" <%= controller_name %> <%= action_name %>">
      <%= render 'layouts/header' %>

      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <% if current_page?(photos_path) %> <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> <% end %>
  </body>
</html>

app/views/layouts/photo-application.html.erb
<!-- http://manateeshiprepair.com/ -->
<!DOCTYPE html>
<html lang="en">
 <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content= "<%= @page_description %>">
    <link rel="shortcut icon" href="favicon.png">
    <title><%= @page_title %> | Manatee Ship Repair &amp; Fabrication Logo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

    <body class=" <%= controller_name %> <%= action_name %>">
      <%= render 'layouts/header' %>

      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/photos/hello.html.erb
<div class="clearfix"></div><br><br>
<div class="clearfix"></div><br><br>
<div class="clearfix"></div><br><br>

<div class="container">
		<% @array.each do |n| %>
		  <%= n %><br />
		<% end %>

		<br />

		ID: <%= @id %><br />
		ID: <%= params[:id] %><br />
		Page: <%= @page %><br />
		Next page: <%= @page.to_i + 1 %><br />

</div>

<div class="clearfix"></div><br><br>
	<% $id = 0 %>
	<% $max = 3 %>
	<% while $id < $max  do %>
		<% src = $id +=1 %>
		<% tag = "(image_tag('https://s3.amazonaws.com/manatee-ship/gallery/manatee-gallery#{src}.jpg', class: 'img-responsive gall'), image_path('https://s3.amazonaws.com/manatee-ship/gallery/manatee-gallery#{src}.jpg') " %>

			<%= "link_to#{tag}"%>

			<div class="clearfix"></div><br><br>
	<% end %>




<div class="clearfix"></div><br><br>
<div class="clearfix"></div><br><br>

app/views/photos/index.html.erb
<div class="gallery">



<section class="main-content">
	<div class="container">

			<% target = "world" %>
			<%= "Hello #{target}" %>


			<div class="clearfix"></div><br><br>

			<%= @photo %><br>

			<div class="clearfix"></div><br><br>





				<% $id = 0 %>
    		<% $max = 3 %>
				<% while $id < $max  do %>
					<% src = $id +=1 %>
					<% path = "https://s3.amazonaws.com/manatee-ship/gallery/manatee-gallery"+"#{src}"+".jpg" %>
					<%= image_tag("#{path}", class: 'img-responsive gall') %>

						<div class="clearfix"></div><br><br>
				<% end %>

				<div class="clearfix"></div><br><br>
				<%= image_tag('https://s3.amazonaws.com/manatee-ship/gallery/manatee-gallery#{src}.jpg', class: 'img-responsive')%>

				<div class="clearfix"></div><br><br>

				<a href="/photos/hello">Hello page 1</a><br />
				<%= link_to('Hello with parameters', {:action => 'hello', :page => 5, :id => 20}) %><br />
			  <%= link_to(image_tag('gallery/#@image_src', alt: 'MANATEE SHIP REPAIR AND FABRICATION PROJECT GALLERY - #@image_title', class: 'img-responsive'), image_path('#@image_path'), data: { lightbox: "example-set", title: '#@image_title' }) %>
		</div>
	</section>
</div>


<section class="main-content">
	<div class="container">
		<h3>A Four Image Set</h3>
		<div>
     <%= link_to(image_tag('http://lokeshdhakar.com/projects/lightbox2/images/thumb-3.jpg'), image_path('http://lokeshdhakar.com/projects/lightbox2/images/image-3.jpg'), data: { lightbox: "example-set", title: 'first photo' }) %>

			    <%= link_to(image_tag('gallery/#@image_src', alt: 'MANATEE SHIP REPAIR AND FABRICATION PROJECT GALLERY - #@image_title', class: 'img-responsive'), image_path('#@image_path'), data: { lightbox: "example-set", title: '#@image_title' }) %>



			<!-- <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-4.jpg" data-lightbox="example-set" data-title="Or press the right arrow on your keyboard.">
				<img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-4.jpg" alt="" />
			</a>

			<a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-5.jpg" data-lightbox="example-set" data-title="The next image in the set is preloaded as you're viewing.">
				<img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-5.jpg" alt="" />
			</a>

			<a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-6.jpg" data-lightbox="example-set" data-title="Click anywhere outside the image or the X to the right to close.">
				<img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-6.jpg" alt="" />
			</a> -->
		</div>
	</div>
</section>





 <!--  # Create an empty array.
    lines = []
    # Use foreach iterator to loop over lines in the file.
    # ... Add chomped lines.
    IO.foreach("list.txt") do |line|
      lines.push(line.chomp())
    end


    lines.each do |v|

    end -->

<!-- <div>
 @photos.each do |photo|
     link_to(image_tag(attachment_url(photo, :image, :fit, 100, 100, format: 'jpg')), attachment_url(photo, :image, :fit, 500, 500, format: 'jpg'), data: { lightbox: "example-set", title: photo.name })
     < equal link_to(image_tag('gallery/#@image_src', alt: 'MANATEE SHIP REPAIR AND FABRICATION PROJECT GALLERY - #@image_alt', class: 'img-responsive'), image_path('#@image_path'), data: { lightbox: "example-set", title: '#@image_title' }) >
   end
</div> -->

<!--
  class Photo
    def initialize(id, image, name, link )
      @image_src=src
      @image_id=id
      @image_path=path
      @image_title=title
    end

    def show_photo()
      puts "< equal link_to(image_tag('gallery/#@image_src', alt: 'MANATEE SHIP REPAIR AND FABRICATION PROJECT GALLERY - #@image_alt', class: 'img-responsive'), image_path('#@image_path'), data: { lightbox: "example-set", title: '#@image_title' }) >"
    end
  end
  # Create Objects
  photo1=Photo.new("gallery1.jpg", "1", "gallery1.jpg", "Image 1")

  # Call Methods
  photo1.show_photo()
 -->
 <!-- resources :sponsors, :only => [:show] -->



<!--  # Create an empty array.
lines = []
# Use foreach iterator to loop over lines in the file.
# ... Add chomped lines.
IO.foreach("list.txt") do |line|
    lines.push(line.chomp())
end


lines.each do |v|

end -->

app/views/static_pages/_segmenter.html.erb
	<script>document.documentElement.className = 'js';</script>
	<section class="demo-1">
		<main>
			<div class="segmenter"></div>
			<div class="trigger-headline trigger-headline--hidden">
				<% unless current_page?(root_path) %>
						<h1><%= @page_title%></h1>
						<h2>MANATEE SHIP REPAIR &amp; FABRICATION</h2>
					<% else %>
						<h1>Manatee</h1>
						<h2>Ship Repair &amp; Fabrication</h2>
				<% end %>
			</div>
		</main>
		<script>
		(function() {
			var headline = document.querySelector('.trigger-headline'),
				trigger = document.querySelector('.segmenter'),
				segmenter = new Segmenter(document.querySelector('.segmenter'), {
					onReady: function() {
							segmenter.animate();
							headline.classList.remove('trigger-headline--hidden');
					}
				});
		})();
		</script>
	</section>

app/views/static_pages/contact.html.erb
<% @page_title = "Contact Us" %>
<% @page_description = "New Subject" %>

<div class="custom-hd">
	<div class="overlay">
	<h1>Contact Us</h1>
	</div>
</div>
<div class="clearfix"></div>

<section class="main-contact">
	<div class="contact-box">
		<div class="block1">
			<h2>Port Manatee Ship Repair &amp; Fabrication</h2>
			<p class="sub">Located in Tampa Bay’s first port of call, Port Manatee.</p>
			<p>Contact us for a quote, or to discuss your specific vessel repair and fabrication needs.</p>
		</div>

		<div class="block2">
			<h4><span>Phone: </span><br>
			<%= number_to_phone(9414172613, delimiter: '-') %></h4>

	  	<h4 class="email"><span>Email: </span><br>
	  	info@manateeshiprepair.com</h4>
	  </div>

		<div class="block3">
		  <h4 class="address">13604 Reeder Road<br>
				Palmetto, FL 34221</h4>
				<div class="clearfix map-br"></div>
				<%= link_to('View Map', 'https://www.google.com/maps/place/13604+Reeder+Rd,+Palmetto,+FL+34221/@27.6373153,-82.5481234,15z/data=!4m2!3m1!1s0x88c321f1253d981d:0x94e36849ead2e9a4', target: '_blank', class: 'map') %>
		</div>
	</div>

	<div class="contact-body"><div class="overlay">
		<div class="container">
			<div class="block-a">
				<div class="card">
					<h4 class="name">Frank Kerney</h4>
					<h5><%= number_to_phone(9082850912, delimiter: '-') %></h5>
					<h5>frank@manateeshiprepair.com</h5>
				</div>
				<%=image_tag('anchor.png', class: 'icon', alt: 'Manatee Ship Repair, contact info page, icon') %>

				<div class="card bottom">
					<h4 class="name">Jim Braukman</h4>
					<h5><%= number_to_phone(7272125234, delimiter: '-') %></h5>
					<h5>jim@manateeshiprepair.com</h5>
				</div>
			</div>

			<div class="address-blocks">
				<div class="block c">
					<h4><span>Shipping address:</span></h4>
						<h4 class="address">210 National Street<br>
						Palmetto, FL 34221</h4>
						<div class="clearfix map-br"></div>
						<%= link_to('View Map', 'https://www.google.com/maps/place/210+National+St,+Palmetto,+FL+34221/@27.636639,-82.562465,17z/data=!3m1!4b1!4m2!3m1!1s0x88c31f55f1c85bf3:0x3bd919b1c72ddc3', target: '_blank', class: 'map') %>
				</div>

				<div class="block d">
					<h4><span>Port Manatee Ship Repair and Fabrication, LLC:</span></h4>
						<h4 class="address">PO Box 2547<br>
						Oldsmar, FL 34677<br>
					</h4>
				</div>

				<%= link_to "View Our Services", services_path, class: 'block link' %>
				<%= link_to "View Our Project Gallery", gallery_path, class: 'block link' %>
			</div>
		</div>
	</div></div>
</section>

app/views/static_pages/home.html.erb
<% @page_title = "Manatee Ship Repair & Fabrication" %>
<% @page_description = "New Subject" %>

  <!--  render 'static_pages/segmenter' %>  -->
  	<script>document.documentElement.className = 'js';</script>
		<section class="demo-1">
			<main>
				<div class="segmenter"></div>
				<div class="trigger-headline trigger-headline--hidden">
					<h1>Port Manatee</h1>
					<h2>Ship Repair &amp; Fabrication</h2>
				</div>
			</main>
			<script>
			(function() {
				var headline = document.querySelector('.trigger-headline'),
					trigger = document.querySelector('.segmenter'),
					segmenter = new Segmenter(document.querySelector('.segmenter'), {
						onReady: function() {
								segmenter.animate();
								headline.classList.remove('trigger-headline--hidden');
						}
					});
			})();
			</script>
		</section>

		<div class="home-s1">
			<div class="overlay">
				<div class="container no-padding">
					<div class="left-block">
						<div class="top">
							<h4>Located in Tampa Bay’s first port of call, Port Manatee.</h4>
							<p>Manatee Ship Repair and Fabrication has a reputation for prompt, cost effective service, and attention to detail. Our team guarantees professional, quality work on every project. Our company leaders have over 80 years of combined experience in vessel repair and fabrication.</p>
							<hr>
						</div>

						<h4>Bondstrand Pipe Repair and Fabrication Specialists</h4>
						<ul>
							<li><i class="rt-icon2-gears"></i> Topside Ship Repairs of all Nature </li>
							<li><i class="rt-icon2-gears"></i> Structural Fabrication </li>
							<li><i class="rt-icon2-gears"></i> Bondstrand Repair and Fabrication </li>
							<li><i class="rt-icon2-gears"></i> Ballast Water Treatment Systems</li>
						</ul>
						<%= link_to 'View All Services', services_path, class: 'service-link left' %>
						<%= link_to 'Bondstrand Pipe Repair', bondstrand_pipe_path, class: 'service-link' %>
					</div>

					<div class="right-block">
						<div class="r1">
							<%= image_tag('pmsr2.jpg', alt: 'Manatee Ship Repair and Fabrication, property image', class: 'img-square one') %>
							<%= image_tag('pmsr.jpg', alt: 'Manatee Ship Repair and Fabrication, property image', class: 'img-square two') %>
						</div>

						<div class="r2">
							<%= image_tag('welding2.jpg', alt: 'Manatee Ship Repair and Fabrication, property image', class: 'img-square three') %>
							<%= image_tag('pmsr3.jpg', alt: 'Manatee Ship Repair and Fabrication, property image', class: 'img-square four') %>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="clearfix"></div>

		<div class="bg-overlay">
			<div class="left">
				<h3><span>We are conveniently located</span><br> at the mouth of the Tampa Bay</h3>
				<div class="title-line"></div>
				<p>Vessel repairs are typically urgent situations that require immediate attention.<br>
				If your vessel is in need of emergency service, accessibility is a huge asset in a repair team.</p>
				<p class="last">Manatee Ship Repair &amp; Fabrication's strategic location allows us to offer timely service to all vessels trading in the Gulf of Mexico and Western Caribbean Sea.</p>
			</div>
			<span class="div"></span>
			<div class="right">
					<h4>Our team has decades of experience swiftly responding to emergency calls, and working effectively in critical circumstances.<br>
					<span> We have the ability to accommodate any Bondstrand projects, land or sea.</span></h4>
			</div>
		</div>

		<div class="home-s3">
			<div class="container no-padding">
				<div class="content-box">
					<div class="top">
						<div class="text">
							<p>View Our Work</p>
							<h3>Take a look at some of our completed projects, in our Project Gallery.</h3>
							<%= link_to 'View Gallery', photos_path, class: 's3-link' %>
						</div>
					</div>

					<div class="bottom">
						<div class="text right">
							<p>Get a Quote</p>
							<h3>Contact us today for an estimate on your vessel repair or fabrication project.</h3>
							<%= link_to 'Contact Us', contact_path, class: 's3-link' %>
						</div>
					</div>
				</div>
			</div>
		</div>




<!-- Valves, Pumps, Winches, Hatch Covers, Structural Repairs, Air Conditioning, Electrical, Hydraulic Systems, Pneumatic Systems, Joinery -->
<!-- We would be honored to bid your repair job and earn your business. Contact us today by phone or email for prompt service and availability. -->
<!--  -->

app/views/static_pages/photos.html.erb
<% @page_title = "Project Gallery" %>
<% @page_description = "New Subject" %>

	<div class="custom-hd">
		<h1>Manatee Project Gallery </h1>
	</div>

<section class="project-gallery">
	<div>
		<% $i = 0 %>
		<% $max = 86 %>
		<% while $i < $max  do %>
			<% tag = $i +=1 %>
			<% link = "https://s3.amazonaws.com/manatee-ship/gallery/manatee-gallery"+"#{tag}"+".jpg" %>
			<% target = "https://s3.amazonaws.com/manatee-ship/gallery/manatee-gallery"+"#{tag}"+".jpg" %>

			<%= link_to(image_tag("#{link}", class: 'img-responsive gall', alt: 'MANATEE SHIP REPAIR AND FABRICATION PROJECT GALLERY'), image_path("#{target}"), data: { lightbox: "example-set"}) %>
		<% end %>
	</div>
</section>


<!--<%= link_to(image_tag('https://s3.amazonaws.com/manatee-ship/gallery/manatee-gallery1.jpg', alt: 'MANATEE SHIP REPAIR AND FABRICATION PROJECT GALLERY - Image 1', class: 'img-responsive gall'), image_path('https://s3.amazonaws.com/manatee-ship/gallery/manatee-gallery1.jpg'), data: { lightbox: "example-set", title: 'Image 1' }) %>-->